# 서버 기본 설정
server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/backTest?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: tanine
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    jpa:
      hibernate:
        ddl-auto: none
mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.booklog.booklogbackend.Model.vo

# jwt 설정
jwt:
  secret: your-very-secure-secret-key-1234567890abcdef
  access-token-expiration: 180000 # 30분 (액세스 토큰)
  refresh-token-expiration: 604800000 # 7일 (리프레시 토큰)

# 로그 설정
logging:
  file:
    name: C:\\WAS_DATA\\application_log\\log.txt
    append: true
  level:
    org.springframework.security: DEBUG
    com.booklog.booklogbackend: DEBUG
    org.mybatis: DEBUG
    com.booklog.booklogbackend.mapper: TRACE
    org.springframework.web: OFF
    java.sql: OFF
    jdbc: OFF
    jdbc.sqlonly: INFO
    jdbc.sqltiming: OFF
    jdbc.audit: OFF
    jdbc.resultset: OFF
    jdbc.resultsettable: INFO
    jdbc.connection: OFF
    com.zaxxer.hikari: INFO
    com.zaxxer.hikari.HikariConfig: INFO
    root: INFO
    catalina: INFO
  logback:
    rollingpolicy:
      file-name-pattern: C:\\WAS_DATA\\application_log\\old\\log-%d{yyyy-MM-dd}.%i.txt
      clean-history-on-start: true
      total-size-cap: 100MB
      max-history: 30
      max-file-size: 100MB
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr([???]: %line){red} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%15.15t] %-40.40logger{39} : [???] : %line  %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"